### ISSUE TITLE
Mongoose Data?

### ISSUE THREAD

**Issue by de-olagundoye** [de-olagundoye/final_project#1]
Is it possible to get the data from my seed.js into my Mongolab Collections?

**Comment by sungchoi** [comment]
@de-olagundoye You mean into your database? Yes.

Assuming your seed.js is a script that connects to your database and adds/inserts objects into it, you need to tell you app to run that code at some point. Or you need to specify how to run that file in your package.json as a script. You run that command the same way you run `npm start`.

**Comment by de-olagundoye** [comment]
When I run it, it only goes into my local DB

**Comment by sungchoi** [comment]
@de-olagundoye Where should it go?

**Comment by de-olagundoye** [comment]
my mongolab collections?

**Comment by de-olagundoye** [comment]
nevermind...i figured it out with node-mongo-seeds.

**Comment by sungchoi** [comment]
@de-olagundoye Nice! You could have also built it into the app.js or run commands through the heroku commandline.
